function [fitresult, gof] = baseline_sub(data)
%CREATEFIT(DATA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: data
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Nov-2018 16:14:20


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], data );

% Set up fittype and options.
ft = fittype( 'poly9' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'data', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
ylabel data
grid on


