% Defines command codes used by mexADQ.dll


% Command codes
MATLAB_SET_LVL_TRIGGER_LEVEL =      1;
MATLAB_SET_LVL_TRIGGER_EDGE =       2;
    RISING_EDGE = 	1;
    FALLING_EDGE = 	0;
MATLAB_SET_LVL_TRIGGER_CHANNEL =    3;
    NO_CH = 	0;
    CH_A = 		1;
    CH_B = 		2;
    CH_C = 		4;
    CH_D = 		8;
    ANY_CH = 	3;
MATLAB_SET_CLOCK_SOURCE	=           4;
    INT_INTREF = 	0;
    INT_EXTREF = 	1;
    EXT = 			2;
    INT_PXIREF =    3;
MATLAB_SET_PLL_FREQ_DIVIDER =       5;
MATLAB_SET_TRIGGER_MODE	=			6;
    USB_TRIGGER_MODE = 		1;
    SW_TRIGGER_MODE = 		1;
    EXTERNAL_TRIGGER_MODE = 2;
    LEVEL_TRIGGER_MODE = 	3;
    INTERNAL_TRIGGER_MODE = 4;
MATLAB_SET_BUFFER_SIZE_PAGES =		7;
MATLAB_ARM_TRIGGER =				8;
MATLAB_DISARM_TRIGGER =				9;
MATLAB_USB_TRIG	=					10;
MATLAB_COLLECT_DATA_ONE_PAGE =		11;  % Obsolete
MATLAB_GET_TRIGGED =				12;  % Obsolete
MATLAB_GET_ACQUIRED =               12;
MATLAB_GET_PAGE_COUNT =				13;
MATLAB_GET_LVL_TRIGGER_EDGE =		14;
MATLAB_GET_LVL_TRIGGER_CHANNEL =	15;
MATLAB_GET_CLOCK_SOURCE =			16;
MATLAB_GET_PLL_FREQ_DIVIDER =		17;
MATLAB_GET_TRIGGER_MODE	=			18;
MATLAB_SET_PRE_TRIGGER_SAMPLES =	19;
MATLAB_GET_BUFFER_SIZE_PAGES =		20;
MATLAB_GET_BUFFER_SIZE =            21;
MATLAB_GET_SAMPLES_PER_PAGE	=		22;
MATLAB_GET_USB_ADDRESS	=			23;
MATLAB_GET_REVISION	=				24;
MATLAB_GET_TRIG_POINT =				25;
MATLAB_GET_OVERFLOW	=				26;
MATLAB_GET_TRIGGED_CH =				27; % Obsolete
MATLAB_GET_TRIGGERED_CH =			27;
MATLAB_SEND_PROCESSOR_COMMAND =		28;
MATLAB_SEND_LONG_PROCESSOR_COMMAND= 29;
MATLAB_GET_BCD_DEVICE =             30;
MATLAB_WRITE_ALGO_REGISTER =		31;
MATLAB_READ_ALGO_REGISTER =         32;
MATLAB_SET_BUFFER_SIZE =            33;
MATLAB_SET_SAMPLE_WIDTH =           34;
MATLAB_GET_TEMPERATURE =            35;
MATLAB_WRITE_EEPROM =               36;
MATLAB_READ_EEPROM =                37;
MATLAB_GET_ERROR_VECTOR =           38;
MATLAB_GET_ADQAPI_REVISION =        39;
MATLAB_DISPLAY_BOARD_SERIAL_NUMBER= 40;
MATLAB_GET_TRIGGER_INFORMATION =    41;
MATLAB_GET_ADQ_TYPE =				42;
MATLAB_GET_TRIGTIME =				43;
MATLAB_GET_MULTIRECORDHEADER =		44;

MATLAB_IS_USB_DEVICE =				45;
MATLAB_IS_PCIE_DEVICE =				46;
MATLAB_RESET_DEVICE	=   		    47;

MATLAB_WRITE_EEPROM_DB =            48;
MATLAB_READ_EEPROM_DB =             49;


MATLAB_MULTI_TRIGGER_SETUP =		50;
MATLAB_MULTI_TRIGGER_GETRECORD =	51;
MATLAB_MULTI_TRIGGER_CLOSE =		52;
MATLAB_SET_TRIGTIMEMODE	=			53;
    SYNC_ON = 	1;
    SYNC_OFF = 	0;
MATLAB_RESET_TRIGTIMER =            54;
MATLAB_SET_AFE_SWITCH =             55;


MATLAB_MEMORY_DUMP =				60;
MATLAB_MEMORY_SHADOW =              61;

MATLAB_SW_TRIG =					71;
MATLAB_COLLECT_RECORD =				72;
MATLAB_GET_TRIGGED_ALL =			73; % Obsolete
MATLAB_GET_ACQUIRED_ALL =			73;
MATLAB_GET_RECORD_SIZE =			74;
MATLAB_GET_NOF_RECORDS =			75;
MATLAB_GET_ACQUIRED_RECORDS =       76;
MATLAB_GET_PCIE_ADDRESS =			77;
MATLAB_WRITE_REGISTER =				78;
MATLAB_READ_REGISTER =				79;
MATLAB_READ_GPIO =					80;
MATLAB_WRITE_GPIO =					81;
MATLAB_SET_DIRECTION_GPIO =			82;
MATLAB_GET_STREAM_STATUS =			83;
MATLAB_SET_STREAM_STATUS =			84;
MATLAB_READ_TRIG =					85;
MATLAB_WRITE_TRIG =					86;
MATLAB_SET_DIRECTION_TRIG =			87;
MATLAB_GET_FIFO_OVERFLOW =			88;
MATLAB_SET_CLOCK_FREQUENCY_MODE =	90;
MATLAB_SET_TRIGGER_HOLDOFF_SAMPLES= 91;
MATLAB_GET_TRIG_TYPE              = 92;
MATLAB_SET_TEST_PATTERN_MODE      = 93;
MATLAB_SET_TEST_PATTERN_CONSTANT  = 94;
MATLAB_SET_LEVEL_TRIG_RESET_LEVEL = 95;
MATLAB_GET_WAITING_FOR_TRIGGER    = 96;
MATLAB_GET_DATA                   = 97;
MATLAB_GET_DATA_SPEED_TEST        = 98;
MATLAB_GET_DATA_WH                = 99;

MATLAB_SET_NUMBER_OF_BITS =         100;
MATLAB_SET_ALGO_STATUS =            101;
MATLAB_SET_ALGO_NYQUIST =           102;
MATLAB_SET_DATA_FORMAT =            103;
MATLAB_SET_SAMPLE_SKIP =            104;
MATLAB_SET_PLL =                    105;
MATLAB_SET_DELAY_LINE_VAL =         106;

MATLAB_COLLECT_RECORD_16BIT =   	110;
MATLAB_GET_DATA_WHTS        =       111;


MATLAB_SET_GAIN_OFFSET =            120;
MATLAB_GET_GAIN_OFFSET =            121;

MATLAB_SET_INTERLEAVING_MODE =		122;
    FOUR_CHANNELS_ABCD =              0;
    TWO_CHANNELS_AC =                 1;
    TWO_CHANNELS_BD =                 2;
    TWO_CHANNELS_ABCD =               3;

MATLAB_GET_EXTERNAL_CLOCK_STATUS =  123;

MATLAB_SET_EXTERNAL_TRIG_POLARITY = 124;
MATLAB_GET_EXTERNAL_TRIG_POLARITY = 125;
MATLAB_ENABLE_CLOCK_REF_OUT =       126;
MATLAB_SET_EXTERNAL_TRIGGER_DELAY = 127;

MATLAB_READ_ADC_CALIBRATION =       130;
MATLAB_WRITE_ADC_CALIBRATION =      131;

MATLAB_SET_PPT_BURST_MODE =         132;
MATLAB_SET_PPT_PERIOD =             133;
MATLAB_SET_PPT_INIT_OFFSET =        134;
MATLAB_SET_PPT_ACTIVE =             135;
MATLAB_INIT_PPT =                   136;
MATLAB_GET_PPT_STATUS =             137;
MATLAB_SET_SAMPLE_DECIMATION =		138;
MATLAB_SET_INTERNAL_TRIGGER_PERIOD=	139;

MATLAB_RESET_INTERLEAVING_IP =      140;
MATLAB_RESET_OVERHEAT =             141;
MATLAB_REBOOT_COM_FPGA_FROM_SECONDARY_IMAGE = 142;
MATLAB_REBOOT_ALG_FPGA_FROM_PRIMARY_IMAGE = 143;
MATLAB_SET_EXTERN_TRIG_MODE =       144;
MATLAB_GET_DATA_MULTI_RECORD_SETUP = 145;
MATLAB_ADC_CALIBRATE =              146;
MATLAB_SET_TRANSFER_BUFFERS =       147;
MATLAB_SET_TRANSFER_TIMEOUT =       148;
MATLAB_SET_CACHE_SIZE =             149;
MATLAB_GET_LAST_ERROR =             150;
MATLAB_GET_LVL_TRIG_LEVEL =         151;

MATLAB_INITTRANSFER	=               152;
MATLAB_GETDSPDATA =                 153;
MATLAB_GETDSPDATANOWAIT =           154;
MATLAB_SETSENDLENGTH =              155;
MATLAB_GETSENDLENGTH =              156;
MATLAB_WAITFORPCIEDMAFINISH =       157;
MATLAB_WRITETODATAEP =              158;
MATLAB_GETPHYSICALADDRESS =         159;
MATLAB_COLLECT_DSPDATA =            160;
MATLAB_SET_CONFIGURATION_TRIG =     161;

MATLAB_SET_DAC_OFFSET_VOLTAGE =     162;
MATLAB_AWG_MALLOC =                 163;
MATLAB_AWG_SEGMENTMALLOC =			173;
MATLAB_AWG_WRITE_SEGMENT =          164;
MATLAB_AWG_ENABLE_SEGMENTS =        165;
MATLAB_AWG_AUTO_REARM =             166;
MATLAB_AWG_ARM =                    167;
MATLAB_AWG_DISARM =                 168;
MATLAB_AWG_CONTINUOUS =             169;
MATLAB_AWG_TRIGMODE =				174;

MATLAB_SETETHERNETPLLFREQ =			175;
	ETH10_FREQ_156_25MHZ = 0;
	ETH10_FREQ_125MHZ = 1;
	ETH1_FREQ_156_25MHZ = 0;
	ETH1_FREQ_125MHZ = 1;
MATLAB_SETPOINTTOPOINTPLLFREQ =		176;
	PP_FREQ_330MHZ = 3;
	PP_FREQ_250MHZ = 2;
	PP_FREQ_156_25MHZ = 1;
	PP_FREQ_125MHZ = 0;
MATLAB_SETETHERNETPLL =				177;
MATLAB_SETPOINTTOPOINTPLL =			178;
MATLAB_SETDIRECTIONMLVDS =			179;

MATLAB_REGISTER_ADDRESS	=		    180;
MATLAB_COLLECT_STREAM_DATA =		181;

MATLAB_SET_INTERLEAVING_IP_ESTIMATION_MODE =	    182;
MATLAB_GET_INTERLEAVING_IP_ESTIMATION_MODE =		183;
MATLAB_SET_INTERLEAVING_IP_CALIBRATION = 184;
MATLAB_GET_INTERLEAVING_IP_CALIBRATION = 185;

MATLAB_SET_INTERNAL_TRIGGER_FREQUENCY = 186;

MATLAB_SEND_IP_COMMAND =			187;

MATLAB_DAC_SPI_WRITE =              188;
MATLAB_DAC_SPI_READ =               189;

MATLAB_GETNGCPARTNUMBER =			190;
MATLAB_GETUSERLOGICPARTNUMBER =		191;

MATLAB_OFFSETDAC_SPI_WRITE =        192;

MATLAB_GET_DATA_PT                = 193;
MATLAB_GET_DATA_PT_16BIT          = 194;

MATLAB_GET_NOF_CHANNELS           = 195;

%WFA 
MATLAB_WFAVG_ARM =                  200;
MATLAB_WFAVG_DISARM =               201;
MATLAB_WFAVG_GETWAVEFORM =          202;
MATLAB_WFAVG_GETSTATUS =            203;
MATLAB_WFAVG_SETUP =                204;
MATLAB_WFAVG_GETONEWAVEFORM =       205;

MATLAB_WRITESTARBDELAY =			206;
MATLAB_GET_LVL_TRIG_EDGE =          207;
MATLAB_GET_SAMPLE_DECIMATION =      208;
MATLAB_GET_EXTERN_TRIG_EDGE =       209;
MATLAB_GET_OUTPUT_WIDTH =           210;
MATLAB_GET_AFE_SWITCH =             211;
MATLAB_GET_EXTERNAL_CLOCK_REFERENCE_STATUS = 212;
MATLAB_GET_BOARD_SERIAL_NUMBER =    213;
MATLAB_GET_CARD_OPTION =            214;
MATLAB_GET_TRIGTIME_SYNCS =         215;
MATLAB_GET_TRIGTIME_CYCLES =        216;
MATLAB_GET_TRIGTIME_START =         217;
MATLAB_GET_DATA_FORMAT =            218;
MATLAB_IS_ALIVE =                   219;
MATLAB_IS_STARTED_OK =              220;
MATLAB_PACKET_STREAMING_SETUP =     221;
MATLAB_PACKET_STREAMING_ARM =       222;
MATLAB_PACKET_STREAMING_DISARM =    223;
MATLAB_GET_INTERLEAVING_IP_BYPASS_MODE = 224;
MATLAB_SET_INTERLEAVING_IP_BYPASS_MODE = 225;
MATLAB_SET_INTERLEAVING_IP_FREQUENCY_CALIBRATION_MODE = 226;
MATLAB_GET_INTERLEAVING_IP_FREQUENCY_CALIBRATION_MODE = 227;
MATLAB_TRIG_OUT_EN =                228;
MATLAB_GET_SAMPLE_SKIP =            229;

MATLAB_ENABLEPXIETRIGGERS =         230;
MATLAB_ENABLEPXIETRIGOUT =          231;
MATLAB_PXIESOFTWARETRIGGER =        232;
MATLAB_SETPXIETRIGDIRECTION =       233;

MATLAB_AWGSETUPTRIGOUT =            234;
MATLAB_AWGTRIGOUTARM =              235;
MATLAB_AWGTRIGOUTDISARM =           236;
MATLAB_AWGSETTRIGGERENABLE =        237;

MATLAB_COLLECT_DATA_NEXT_PAGE =     238;
MATLAB_GET_DATA_STREAM         =    239;
MATLAB_GET_PCIE_LINK_WIDTH =        240;
MATLAB_GET_PCIE_LINK_RATE =         241;

MATLAB_REBOOT_ADQ_FROM_FLASH =      242;

MATLAB_TRIGOUTENABLE =              243;
MATLAB_SETEXTTRIGTHRESHOLD =        244;
MATLAB_HASTRIGHARDWARE =            245;
MATLAB_HASTRIGOUTHARDWARE =         246;
MATLAB_HASVARIABLETRIGTHRESHOLD =   247;

MATLAB_LISTDEVICES =                248;
MATLAB_OPENDEVICEINTERFACE =        249;

MATLAB_GETMAXNOFRECORDSFROMNOFSAMPLES = 250;
MATLAB_GETMAXNOFSAMPLESFROMNOFRECORDS = 251;

MATLAB_WRITEUSERREGISTER =          252;
MATLAB_READUSERREGISTER =           253;

MATLAB_TS_SETUP =                      254;
MATLAB_TS_SETREGISTER =                255;
MATLAB_TS_SETSERIAL =                  256;
MATLAB_TS_ARM =                        257;
MATLAB_TS_DISARM =                     258;
MATLAB_GET_TS_RECORDS =                259;
MATLAB_TS_GET_NOF_RECORDS_COMPLETED =  260;
MATLAB_HASADJUSTABLEBIAS =             261;
MATLAB_SETBIASDACPERCENTAGE =          262;

MATLAB_SPISEND =                       263;
MATLAB_SETUPDEVICE =                   264;
MATLAB_ENABLEERRORTRACE =              265;
MATLAB_ENABLEERRORTRACEAPPEND =        266;
MATLAB_SETUPLEVELTRIGGER =             267;

% Data format values
ADQ108_DATA_FORMAT_PACKED_8BIT =   0;

ADQ112_DATA_FORMAT_PACKED_12BIT =   0;
ADQ112_DATA_FORMAT_UNPACKED_12BIT = 1;
ADQ112_DATA_FORMAT_UNPACKED_16BIT = 2;
ADQ112_DATA_FORMAT_UNPACKED_32BIT = 3;

ADQ114_DATA_FORMAT_PACKED_14BIT =   0;
ADQ114_DATA_FORMAT_UNPACKED_14BIT = 1;
ADQ114_DATA_FORMAT_UNPACKED_16BIT = 2;
ADQ114_DATA_FORMAT_UNPACKED_32BIT = 3;

ADQ214_DATA_FORMAT_PACKED_14BIT =   0;
ADQ214_DATA_FORMAT_UNPACKED_14BIT = 1;
ADQ214_DATA_FORMAT_UNPACKED_16BIT = 2;
ADQ214_DATA_FORMAT_UNPACKED_32BIT = 3;

ADQ212_DATA_FORMAT_PACKED_12BIT =   0;
ADQ212_DATA_FORMAT_UNPACKED_12BIT = 1;
ADQ212_DATA_FORMAT_UNPACKED_16BIT = 2;
ADQ212_DATA_FORMAT_UNPACKED_32BIT = 3;

ADQ1600_DATA_FORMAT_PACKED_16BIT = 0;
ADQ1600_DATA_FORMAT_UNPACKED_16BIT = 1;
ADQ1600_DATA_FORMAT_UNPACKED_32BIT = 3;

% ADX command interface
CMD_ADX_RESET                      = 1;
CMD_ADX_SETBANDOFINTEREST          = 2;
CMD_ADX_GETBANDOFINTEREST          = 3;
CMD_ADX_SET_MODE                   = 4;
CMD_ADX_GET_MODE                   = 5;
CMD_ADX_BYPASS                     = 6;
CMD_ADX_ENABLE                     = 7;
CMD_ADX_SETGLOBALS                 = 8;
CMD_ADX_GETGLOBALS                 = 9;
CMD_ADX_SETPARAMETERS              = 10;
CMD_ADX_GETPARAMETERS              = 11;
CMD_ADX_SETSTATE                   = 12;
CMD_ADX_GETSTATE                   = 13;
CMD_ADX_GETVERSION                 = 14;

CMD_ADX_READBACK                   = hex2dec('FFFFFFFF');


