function [fitresult, gof] = delayfitT(fd, fit1)
%CREATEFIT(FD,FIT1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : fd
%      Y Output: fit
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Jan-2016 10:51:26


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( fd, fit1 );

% Set up fittype and options.
ft = fittype( '-(0.0099*(a+x).^2)./b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-6000 3000];
opts.StartPoint = [0 300];
opts.Upper = [6000 0];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'fit vs. fd', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'fd' );
ylabel( 'fit1' );
grid on


