function width = fwhm(x)
%CREATEFIT(X,GATERATIO1515_000_135_MEAN)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: gateratio1515_000_135_mean
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Aug-2016 10:56:58


%% Fit: 'untitled fit 1'.
width = x*2.35482/1.414;


% Display the results.
fprintf('The FWHM is %d mm', width);


