function [fitresult, gof] = Gauss8(x, hdata)
%CREATEFIT(X,HDATA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: hdata
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Nov-2018 15:53:11


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, hdata );

% Set up fittype and options.
ft = fittype( 'gauss8' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.Robust = 'LAR';
opts.StartPoint = [10506 701 18.0744390837987 10441 543 18.6432843931159 9509.99999994119 793 22.911941916872 7767 414 26.4360360653203 6267.16889519178 830 35.517656071712 5938.2098428041 341 40.585275443381 5813.90986450462 451 43.01655641844 5180.75550846116 901 57.1563998894686];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'hdata vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel x
ylabel hdata
grid on


