function [fitresult, gof] = MaxBoltzfit(x1, y2gate74_2)
%CREATEFIT(X1,Y2GATE74_2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x1
%      Y Output: y2gate74_2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Dec-2015 12:36:47


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x1, y2gate74_2 );

% Set up fittype and options.
ft = fittype( '(a./((x).^2)).*exp(-b./((x).^2))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Algorithm = 'Levenberg-Marquardt';
opts.Display = 'Off';
opts.StartPoint = [0.26380291652199 0.145538980384717];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'y2gate74_2 vs. x1', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
% xlabel( 'x1' );
% ylabel( 'y2gate74_2' );
% grid on


