function [fitresult, gof] = MaxBoltfullfit(t, gate165_3mm)
%CREATEFIT(T,GATE165_3MM)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: gate165_3mm
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Jan-2016 17:11:38


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, gate165_3mm );

% Set up fittype and options.
ft = fittype( '(a./((x-d).^2)).*exp(b./((x-d).^2))+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [800 -2000 -10 0];
opts.StartPoint = [0.0377388662395521 0.885168008202475 0.913286827639239 0.796183873585212];
opts.Upper = [Inf 0 0 10];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'gate165_3mm vs. t', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 't' );
ylabel( 'gate165_3mm' );
grid on


