function [fitresult, gof] = maxwellvelofit(gate74_velo, gate74_yielnor)
%CREATEFIT(GATE74_VELO,GATE74_YIELNOR)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : gate74_velo
%      Y Output: gate74_yielnor
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Jan-2016 18:20:26


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( gate74_velo, gate74_yielnor );

% Set up fittype and options.
% ft = fittype( '4*pi*a*(0.135/(2*pi*8.31446*T))^1.5*(x-v).^2.*exp(-0.135*(x-v).^2/(2*8.31446*T))', 'independent', 'x', 'dependent', 'y' );
ft = fittype( '4*pi*a*(0.165/(2*pi*8.31446*T))^1.5*(x-v).^2.*exp(-0.165*(x-v).^2/(2*8.31446*T))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0.01 0];
opts.StartPoint = [665 1.232 0];
opts.Upper = [2000 1000 300];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'gate74_yielnor vs. gate74_velo', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'gate74_velo' );
ylabel( 'gate74_yielnor' );
grid on


