function [fitresult, gof] = splinesmooth(x, gate1_ave)
%CREATEFIT(X,GATE1_AVE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: gate1_ave
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Aug-2016 14:41:08


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, gate1_ave );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.Normalize = 'on';
opts.SmoothingParam = 0.999299682387876;
% opts.SmoothingParam = 0.27654625724810217; %0.0158113562186306; %0.00357186496913603;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
plot(x,gate1_ave,'o','markersize',6);
hold on;
plot( fitresult );
% h = plot( fitresult, xData, yData );
legend( 'gate1_ave vs. x', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel( 'x' );
ylabel( 'gate1_ave' );
grid on


