function [fitresult, gof] = SFGpfitfc(FcC11wn, FcC11n)
%CREATEFIT(FCC11WN,FCC11N)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : FcC11wn
%      Y Output: FcC11n
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Jan-2023 16:34:01


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( FcC11wn, FcC11n );

% Set up fittype and options.
ft = fittype( 'abs((b*x+c)*exp(i*f)+(A01)./((w01)-(x)+i*(G01))+(A02)./((w02)-(x)+i*(G02))+(A03)./((w03)-(x)+i*(G03))+(A04)./((w04)-(x)+i*(G04))).^2', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';

opts.Lower = [0 0 0 0 0 0 0 0 -Inf -Inf -3.14 2834 2906 2985 2500];
opts.StartPoint = [1 1 1 100 10 10 10 300 0.450923706430945 0.547008892286345 0.296320805607773 2849 2916 3100 2687];
opts.Upper = [Inf Inf Inf Inf 40 40 26 Inf Inf Inf 3.14 2864 2926 3115 4000];
% opts.Lower = [0 0 0 0 0 0 0 0 -Inf -Inf -3.14 2834 2906 2985 2500];
% opts.StartPoint = [1 1 1 100 10 10 10 300 0.450923706430945 0.547008892286345 0.296320805607773 2849 2916 3100 2687];
% opts.Upper = [Inf Inf Inf Inf 30 30 30 Inf Inf Inf 3.14 2864 2926 3115 4000];

% opts.Lower = [0 0 0 0 0 0 0 0 -Inf -Inf -Inf 2835 2910 3075 0];
% opts.StartPoint = [0.622055131485066 0.350952380892271 0.513249539867053 0.401808033751942 10 10 10 100 0.239952525664903 0.41726706908437 0.0496544303257421 2855 2920 3095 2700];
% opts.Upper = [Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf Inf 2875 2930 3115 Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'FcC11n vs. FcC11wn', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'FcC11wn', 'Interpreter', 'none' );
ylabel( 'FcC11n', 'Interpreter', 'none' );
grid on


