function [fitresult, gof] = SFGpfit_linB(wn_H, H_SFG_NM)
%CREATEFIT(WN_H,H_SFG_NM)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : wn_H
%      Y Output: H_SFG_NM
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Mar-2022 00:06:29


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( wn_H, H_SFG_NM );

% Set up fittype and options.
ft = fittype( 'abs(m*x+(c)+(A01)*exp(i*f)./((w01)-(x)+i*(G01))).^2', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 -Inf 0 -Inf 0];
opts.Robust = 'Bisquare';
opts.StartPoint = [0.432391503783462 0.825313795402046 0.083469814858914 0.1332 0.0967 2060];
opts.Upper = [Inf Inf Inf 6.28 Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'H_SFG_NM vs. wn_H', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'wn_H', 'Interpreter', 'none' );
% ylabel( 'H_SFG_NM', 'Interpreter', 'none' );
% grid on


