function [fitresult, gof] = SFGpfitfcell(FcC11wn, FcC11n)
%CREATEFIT(FCC11WN,FCC11N)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : FcC11wn
%      Y Output: FcC11n
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Jan-2023 16:01:07


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( FcC11wn, FcC11n );

% Set up fittype and options.
% ft = fittype( 'abs((b*x+c)*exp(i*f)+(A01)./((w01)-(x)+i*(G01))+(A02)./((w02)-(x)+i*(G02))+(A03)./((w03)-(x)+i*(G03))+(A04)./((w04)-(x)+i*(G04))).^2', 'independent', 'x', 'dependent', 'y' );
% opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
% opts.Display = 'Off';
% opts.Lower = [0 0 0 -Inf 0 0 0 0 -100 -Inf -3.14 3000 3150 3300 0];
% opts.StartPoint = [4 4 4 1 10 10 40 200 0.2 -1.5 0.301246330279491 3095 3250 3410 3600];
% opts.Upper = [40 10 100 1000 100 60 60 5000 100 100 3.14 3115 3270 3430 5000];
ft = fittype( 'abs((b*x+c)*exp(i*f)+(A01)./((w01)-(x)+i*(G01))+(A02)./((w02)-(x)+i*(G02))+(A03)./((w03)-(x)+i*(G03))+(A04)./((w04)-(x)+i*(G04))).^2', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-40 -40 -40 -1000 0 0 0 0 -100 -Inf 1.2 3090 3220 3400 0];
opts.StartPoint = [4 4 4 1 80 80 40 100 0.2 4 1.388 3095 3250 3410 2000];
opts.Upper = [40 40 100 1000 100 100 100 5000 100 5 1.5 3110 3290 3465 5000];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'FcC11n vs. FcC11wn', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'FcC11wn', 'Interpreter', 'none' );
ylabel( 'FcC11n', 'Interpreter', 'none' );
grid on


