function [fitresult, gof] = SFGpfit(wn_CO, CO_SFG_NM)
%CREATEFIT(WN_CO,CO_SFG_NM)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : wn_CO
%      Y Output: CO_SFG_NM
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Mar-2022 22:50:39


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( wn_CO, CO_SFG_NM );

% Set up fittype and options.
ft = fittype( 'abs((c)+(A01)*exp(i*f)./((w01)-(x)+i*(G01))).^2', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 0 1900];
opts.Robust = 'Bisquare';
opts.StartPoint = [0.0714454646006424 20.521649842464284 0.935832706405493 0.659605252908307 2080];
opts.Upper = [Inf Inf Inf 6.28 2200];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'CO_SFG_NM vs. wn_CO', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'wn_CO', 'Interpreter', 'none' );
% ylabel( 'CO_SFG_NM', 'Interpreter', 'none' );
% grid on


