function [fitresult, gof] = SFGpenfit(wnx, PenI)
%CREATEFIT(WNX,PENI)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input: wnx
%      Y Output: PenI
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Feb-2025 21:10:15


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( wnx, PenI );

% Set up fittype and options.
ft = fittype( 'abs((c)+(A01)*exp(i*f)./((w01)-(x)+i*(G01))).^2', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0 -4 2950];
opts.StartPoint = [2 13 1.4 -1.8 2960];
opts.Upper = [Inf 20 Inf 4 2980];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'PenI vs. wnx', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'wnx', 'Interpreter', 'none' );
% ylabel( 'PenI', 'Interpreter', 'none' );
% grid on


